In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pyreadstat as prs

In [2]:
nfhs_dist = pd.read_excel(r"D:\diagnomitra_public_data\raw_data\NFHS_5_India_Districts_Factsheet_Data.xls")

In [3]:
nfhs_dist.head()

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,Nicobars,Andaman & Nicobar Islands,882,764,125,78.01,22.98,973.31,927.41,98.01,...,32.86,11.06,46.97,13.35,13.16,5.37,63.46,76.79,29.59,64.49
1,North & Middle Andaman,Andaman & Nicobar Islands,874,789,108,82.66,19.82,949.82,844.43,100.00,...,22.62,5.97,32.20,1.70,0.25,15.84,46.77,70.47,5.08,45.26
2,South Andaman,Andaman & Nicobar Islands,868,844,134,84.68,20.95,967.48,934.92,96.53,...,17.88,6.09,26.90,1.32,0.67,8.00,19.60,50.76,1.72,32.81
3,Srikakulam,Andhra Pradesh,874,780,100,59.99,20.71,1139.51,1162.58,94.96,...,14.37,5.51,22.89,1.04,0.23,3.76,7.09,21.32,0.55,28.26
4,Vizianagaram,Andhra Pradesh,902,853,134,55.95,20.56,1114.35,898.03,95.42,...,14.83,6.43,25.13,4.90,0.63,7.33,11.41,21.47,0.80,32.30

In [4]:
nfhs_dist.shape

(707, 109)

In [5]:
nfhs_dist.describe()

,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),Population living in households with electricity (%),Population living in households with an improved drinking-water source1 (%),...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
count,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,...,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.00000
mean,900.502122,1024.019802,144.002829,71.507822,26.356874,1020.696139,937.990184,91.064795,96.996025,93.726054,...,16.253621,6.042518,24.759661,1.565827,0.652900,0.700495,11.614965,40.599646,2.912631,23.19075
std,69.273371,177.064999,31.953268,10.311666,5.296601,73.367114,165.625452,9.392697,4.354175,8.714690,...,4.336475,2.573082,6.768313,2.774292,1.566614,1.468252,11.943028,14.081028,6.079181,13.36201
min,213.000000,216.000000,17.000000,45.360000,15.980000,754.980000,-1261.450000,51.580000,68.350000,41.180000,...,5.290000,0.830000,10.020000,0.000000,0.000000,0.000000,0.060000,6.750000,0.000000,0.07000
25%,882.000000,911.000000,124.000000,64.395000,22.505000,969.055000,864.850000,87.030000,96.390000,92.030000,...,13.190000,4.105000,19.825000,0.190000,0.000000,0.000000,4.090000,30.420000,0.270000,13.58500
50%,908.000000,1020.000000,145.000000,71.340000,25.360000,1013.260000,930.040000,94.890000,98.650000,96.980000,...,16.250000,5.830000,24.420000,0.550000,0.210000,0.280000,7.670000,42.490000,0.500000,20.16000
75%,931.000000,1141.000000,164.000000,78.970000,29.530000,1065.530000,1014.575000,97.745000,99.515000,99.250000,...,18.845000,7.555000,28.970000,1.520000,0.500000,0.690000,14.765000,50.970000,1.710000,30.89000
max,990.000000,1621.000000,241.000000,99.160000,50.560000,1331.640000,1484.970000,100.000000,100.000000,100.000000,...,32.860000,19.460000,49.610000,23.220000,14.550000,15.840000,70.580000,80.560000,42.770000,68.38000

In [6]:
nfhs_dist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Columns: 109 entries, District Names to Men age 15 years and above who consume alcohol (%)
dtypes: float64(75), int64(3), object(31)
memory usage: 602.2+ KB

In [7]:
nfhs_dist.isnull().mean().sort_values()

District Names                                                                           0.0
State/UT                                                                                 0.0
Number of Households surveyed                                                            0.0
Number of Women age 15-49 years interviewed                                              0.0
Number of Men age 15-54 years interviewed                                                0.0
                                                                                        ...
Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)    0.0
Women age 15 years and above who use any kind of tobacco (%)                             0.0
Men age 15 years and above who use any kind of tobacco (%)                               0.0
Women age 15 years and above who consume alcohol (%)                                     0.0
Men age 15 years and above who consume alcohol (%)                                       0.0
Length: 109, dtype: float64

In [9]:
nfhs_dist.columns = nfhs_dist.columns.str.strip()

In [10]:
suspicious_cols = []
for col in nfhs_dist.columns:
    if nfhs_dist[col].dtype == object:
        suspicious_cols.append(col)

In [11]:
len(suspicious_cols)

31

In [12]:
nfhs_dist[suspicious_cols[20:31]]

,Children age 12-23 months who received most of their vaccinations in a private health facility (%),Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%),Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%),Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%),Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%),Children under age 6 months exclusively breastfed16 (%),Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%),"Breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)","Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)","Total children age 6-23 months receiving an adequate diet16, 17 (%)",Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%)
0,-0.01,*,*,*,-85.73,*,*,-19.37,*,-18.71,*
1,*,*,*,*,*,*,*,-6.46,*,-5.92,*
2,-4.33,*,*,*,-77.34,*,*,-22.34,*,23.49,*
3,-2.99,*,*,*,-79.74,*,*,-13.98,*,16.14,*
4,-0.01,*,*,*,-83.54,*,*,-2.47,*,1.75,*
...,...,...,...,...,...,...,...,...,...,...,...
702,0,*,*,*,-60.86,-73.48,*,27.2,*,27.55,-47.39
703,0,*,*,*,72.14,*,*,20.89,*,21.78,-62.9
704,0,*,*,*,72.45,*,*,21.45,*,20.93,-66.42
705,2.43,-81.18,-48.93,-69.7,86.25,*,*,31.37,*,31.05,49.44
706,5.02,*,*,*,56.55,*,*,36.52,*,34.1,-63.66

In [13]:
for col in suspicious_cols[2:]:
    nfhs_dist[col] = nfhs_dist[col].replace("*", pd.NA)

In [17]:
for col in suspicious_cols[2:]:
    nfhs_dist[col] = nfhs_dist[col].abs()

In [28]:
for col in suspicious_cols[2:]:
    nfhs_dist[col] = pd.to_numeric(nfhs_dist[col], errors = "coerce")

In [38]:
int_cols = []
for col in nfhs_dist.columns:
    if nfhs_dist[col].dtype == int:
        int_cols.append(col)

In [40]:
DDnfhs_dist[int_cols]

,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed
0,882,764,125
1,874,789,108
2,868,844,134
3,874,780,100
4,902,853,134
...,...,...,...
702,917,1089,148
703,910,1002,137
704,873,957,131
705,912,1190,184
706,915,1088,163

In [41]:
nfhs_dist.to_excel(r"D:\diagnomitra_public_data\cleaned_data\NFHS_District.xlsx")